name: LernPaper
version: '${project.version}'
main: LernPaper.Main
api-version: 1.18
authors: [ TantaiHaha ]
description: Lern Plugin v.2
commands:
  tantaihaha:
    description: Dev Commamds
    usage: /tantaihaha <action> <args[1]>
  bar:
    description: add Tps bar
    usage: /bar
  c:
    description: Enter Creative World
    usage: /c